#Playbook to grab facts from the FW, it will gather facts related to the hostname, serial #, model, PAN-OS version, firewall uptime, HA and the number
# of active sessions
---
- name: Grab Palo Alto facts
  hosts: palo
  connection: local
 
  collections:
    - paloaltonetworks.panos

#Refer to setPA.yml comments for explaination 
  vars:
    device:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'

#Using these tasks we grab facts about the FWs to quickly create an audit report

  tasks:
    - name: Get facts
      panos_facts:
        provider: '{{device}}'
    
    - name: Display hostname 
      debug:  
        msg: "Hostname: {{ansible_net_hostname}}"

    - name: Display Serial number of the local node 
      debug: 
        msg: "Serial number of local node {{ansible_net_serial }}"

    - name: Display model, PAN-OS version
      debug:
        msg: "Model: {{ ansible_facts['net_model'] }}, version: {{ ansible_facts['net_version'] }}"

    - name: Display firewall up time 
      debug:  
        msg: "Up time: {{ansible_net_uptime}}"
    
    - name: Is High availablity enabled? 
      debug:  
        msg: "High availablity: {{ansible_net_ha_enabled}}"
    
    - name: Display number of active sessions firewall
      debug: 
        msg: "Current active sessions: {{ansible_net_session_usage}}"