#Playbook used to set configurations on both firewalls
---
- name: Set Palo alto configurations
  hosts: palo
#palo is the group variable which houses both fws 
  connection: local
# panos collections 
  collections:
    - paloaltonetworks.panos
# variables used to pass to the provider module, will pull the values of these inside the host_vars folder 
  vars:
    device:
      ip_address: '{{ ip_address }}'
      username: ' {{ username }} '
      password: ' {{ password }} '

  tasks:
    - name: Set hostname, dns servers, NTP servers, panorama primary/secondary 
      panos_mgtconfig:
        provider: '{{ device }} '
# inventory_hostname will set the hostname to the variable specified inside the inventory file. 
        hostname: "{{ inventory_hostname }}"
        dns_server_primary: "1.1.1.1"
        dns_server_secondary: "1.1.1.2"
        panorama_primary: "1.1.1.3"
        panorama_secondary: "1.1.1.4"
        ntp_server_primary: "1.1.1.5"
        ntp_server_secondary: "1.1.1.6"

#Zones must be configured first but creating the policy because the policy references zones, if zones aren't created policy will return an error
#Tasks are made to create the internal and external zones 

    - name: Configure internal zone
      panos_zone:
        provider: '{{ device }} '
        zone: 'internal'
        mode: 'layer3'

    - name: Configure external zone
      panos_zone:
        provider: '{{ device }} '
        zone: 'external'
        mode: 'layer3'

#Task is to allow access for https access from source 172.18.0.1 to any destination
    - name: Set https policy on firewall
      panos_security_rule:
        provider: '{{ device }} '
        rule_name: 'Allow https'
        description: 'Allows https'
        source_zone: ['internal']
        destination_zone: ['external']
        source_ip: ['172.18.0.1']
        source_user: ['any']
        destination_ip: ['any']
        category: ['any']
        application: ['any']
        service: ['service-https']
        hip_profiles: ['any']
        action: 'allow'      
# This task is used to commit the changes onto the firewall, alternatively I believe you can commit the changes yourself or have the changes be returned before commiting
    - name: Commit config on firewall 
      panos_commit:
        provider: '{{ device }} '
