---
- name: Set Palo alto configurations
  hosts: palo
  connection: local
 
  collections:
    - paloaltonetworks.panos
  vars:
    device:
      ip_address: '{{ ip_address }}'
      username: ' {{ username }} '
      password: ' {{ password }} '

  tasks:
    - name: Set hostname, dns servers, NTP servers, panorama primary/secondary 
      panos_mgtconfig:
        provider: '{{ device }} '
        hostname: "{{ inventory_hostname }}"
        dns_server_primary: "1.1.1.1"
        dns_server_secondary: "1.1.1.2"
        panorama_primary: "1.1.1.3"
        panorama_secondary: "1.1.1.4"
        ntp_server_primary: "1.1.1.5"
        ntp_server_secondary: "1.1.1.6"

    - name: Configure internal zone
      panos_zone:
        provider: '{{ device }} '
        zone: 'internal'
        mode: 'layer3'

    - name: Configure external zone
      panos_zone:
        provider: '{{ device }} '
        zone: 'external'
        mode: 'layer3'

    - name: Set https policy on firewall
      panos_security_rule:
        provider: '{{ device }} '
        rule_name: 'Allow https'
        description: 'Allows https'
        source_zone: ['internal']
        destination_zone: ['external']
        source_ip: ['172.18.0.1']
        source_user: ['any']
        destination_ip: ['any']
        category: ['any']
        application: ['any']
        service: ['service-https']
        hip_profiles: ['any']
        action: 'allow'      

    - name: Commit config on firewall 
      panos_commit:
        provider: '{{ device }} '
